[2022-11-25 03:52:16,123] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-24T00:00:00+00:00 [queued]>
[2022-11-25 03:52:16,195] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-24T00:00:00+00:00 [queued]>
[2022-11-25 03:52:16,197] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 03:52:16,198] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-25 03:52:16,200] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 03:52:16,306] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-24 00:00:00+00:00
[2022-11-25 03:52:16,324] {standard_task_runner.py:52} INFO - Started process 77 to run task
[2022-11-25 03:52:16,357] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-24T00:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp1u9rnjm4', '--error-file', '/tmp/tmpps59fawg']
[2022-11-25 03:52:16,362] {standard_task_runner.py:80} INFO - Job 275: Subtask checkfiles.check_energy_file_2
[2022-11-25 03:52:16,511] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-25 03:52:16,941] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-24T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-25 03:52:17,073] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-11-25 03:52:17,078] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 77. PIDs of all processes in the group: [77]
[2022-11-25 03:52:17,140] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 77
[2022-11-25 03:52:17,143] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-11-25 03:52:17,144] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-11-25 03:52:17,213] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1549, in _execute_task_with_callbacks
    self.clear_xcom_data()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 33, in create_session
    session.commit()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1423, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 833, in commit
    self._connections.values()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-11-25 03:52:17,238] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221124T000000, start_date=20221125T035216, end_date=20221125T035217
[2022-11-25 03:52:17,286] {standard_task_runner.py:97} ERROR - Failed to execute job 275 for task checkfiles.check_energy_file_2 (Task received SIGTERM signal; 77)
[2022-11-25 03:52:17,327] {process_utils.py:75} INFO - Process psutil.Process(pid=77, status='terminated', exitcode=1, started='03:52:15') (77) terminated with exit code 1
[2022-11-25 03:52:17,328] {local_task_job.py:156} INFO - Task exited with return code 143
[2022-11-25 03:52:17,463] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
