[2022-11-22 02:59:31,140] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 02:59:31,215] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 02:59:31,219] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 02:59:31,221] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 02:59:31,222] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 02:59:31,320] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 02:59:31,348] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2022-11-22 02:59:31,353] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp7vw66i6g', '--error-file', '/tmp/tmph3fq0pwl']
[2022-11-22 02:59:31,358] {standard_task_runner.py:80} INFO - Job 76: Subtask checkfiles.check_energy_file_2
[2022-11-22 02:59:31,449] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 02:59:31,904] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 02:59:33,107] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 02:59:33,116] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 02:59:33,123] {subprocess.py:74} INFO - Running command: ['bash', '-c', './utilites/check_file.sh ./storage//opt/***']
[2022-11-22 02:59:33,158] {subprocess.py:85} INFO - Output:
[2022-11-22 02:59:33,171] {subprocess.py:92} INFO - bash: line 1: ./utilites/check_file.sh: No such file or directory
[2022-11-22 02:59:33,174] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 02:59:33,276] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 02:59:33,301] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T025931, end_date=20221122T025933
[2022-11-22 02:59:33,402] {standard_task_runner.py:97} ERROR - Failed to execute job 76 for task checkfiles.check_energy_file_2 (Bash command failed. The command returned a non-zero exit code 127.; 63)
[2022-11-22 02:59:33,462] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 02:59:33,673] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:03:27,786] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:03:27,837] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:03:27,838] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:27,840] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:03:27,841] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:27,908] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:03:27,919] {standard_task_runner.py:52} INFO - Started process 76 to run task
[2022-11-22 03:03:27,932] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpa6li332l', '--error-file', '/tmp/tmp58dz6r20']
[2022-11-22 03:03:27,935] {standard_task_runner.py:80} INFO - Job 81: Subtask checkfiles.check_energy_file_2
[2022-11-22 03:03:28,019] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:03:28,270] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:03:28,666] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:03:28,670] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 03:03:28,672] {subprocess.py:74} INFO - Running command: ['bash', '-c', './utilites/check_file.sh ./storage//opt/***']
[2022-11-22 03:03:28,701] {subprocess.py:85} INFO - Output:
[2022-11-22 03:03:28,709] {subprocess.py:92} INFO - bash: line 1: ./utilites/check_file.sh: No such file or directory
[2022-11-22 03:03:28,711] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 03:03:28,796] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 03:03:28,816] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T030327, end_date=20221122T030328
[2022-11-22 03:03:28,866] {standard_task_runner.py:97} ERROR - Failed to execute job 81 for task checkfiles.check_energy_file_2 (Bash command failed. The command returned a non-zero exit code 127.; 76)
[2022-11-22 03:03:28,957] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 03:03:29,161] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:06:34,315] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:06:34,380] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:06:34,382] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:06:34,390] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:06:34,391] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:06:34,475] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:06:34,495] {standard_task_runner.py:52} INFO - Started process 102 to run task
[2022-11-22 03:06:34,530] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpf3c5wj_a', '--error-file', '/tmp/tmpu0ys1ju0']
[2022-11-22 03:06:34,534] {standard_task_runner.py:80} INFO - Job 91: Subtask checkfiles.check_energy_file_2
[2022-11-22 03:06:34,646] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:06:35,013] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:06:36,095] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:06:36,102] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 03:06:36,106] {subprocess.py:74} INFO - Running command: ['bash', '-c', './utilites/check_file.sh ./storage/energy_2.csv']
[2022-11-22 03:06:36,331] {subprocess.py:85} INFO - Output:
[2022-11-22 03:06:36,344] {subprocess.py:92} INFO - bash: line 1: ./utilites/check_file.sh: No such file or directory
[2022-11-22 03:06:36,349] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 03:06:36,598] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 03:06:36,627] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T030634, end_date=20221122T030636
[2022-11-22 03:06:36,736] {standard_task_runner.py:97} ERROR - Failed to execute job 91 for task checkfiles.check_energy_file_2 (Bash command failed. The command returned a non-zero exit code 127.; 102)
[2022-11-22 03:06:36,809] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 03:06:37,236] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:09:13,654] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:09:13,720] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:09:13,721] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:13,722] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:09:13,725] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:13,824] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:09:13,842] {standard_task_runner.py:52} INFO - Started process 150 to run task
[2022-11-22 03:09:13,865] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpo_eufu2l', '--error-file', '/tmp/tmpdf2v21z0']
[2022-11-22 03:09:13,867] {standard_task_runner.py:80} INFO - Job 106: Subtask checkfiles.check_energy_file_2
[2022-11-22 03:09:13,930] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:09:14,179] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:09:14,821] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:09:14,830] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 03:09:14,834] {subprocess.py:74} INFO - Running command: ['bash', '-c', './utilities/check_file.sh ./storage/energy_2.csv']
[2022-11-22 03:09:14,904] {subprocess.py:85} INFO - Output:
[2022-11-22 03:09:14,918] {subprocess.py:92} INFO - bash: line 1: ./utilities/check_file.sh: No such file or directory
[2022-11-22 03:09:14,921] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 03:09:15,059] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 03:09:15,078] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T030913, end_date=20221122T030915
[2022-11-22 03:09:15,146] {standard_task_runner.py:97} ERROR - Failed to execute job 106 for task checkfiles.check_energy_file_2 (Bash command failed. The command returned a non-zero exit code 127.; 150)
[2022-11-22 03:09:15,193] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 03:09:15,396] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:12:52,057] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:12:52,104] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:12:52,105] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:12:52,106] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:12:52,106] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:12:52,172] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:12:52,184] {standard_task_runner.py:52} INFO - Started process 175 to run task
[2022-11-22 03:12:52,198] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmparb2kup5', '--error-file', '/tmp/tmprk18gq7y']
[2022-11-22 03:12:52,200] {standard_task_runner.py:80} INFO - Job 115: Subtask checkfiles.check_energy_file_2
[2022-11-22 03:12:52,263] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:12:52,509] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:12:52,980] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:12:52,984] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 03:12:52,994] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/utilities/check_file.sh /opt/***/utilities/storage/energy_2.csv']
[2022-11-22 03:12:53,033] {subprocess.py:85} INFO - Output:
[2022-11-22 03:12:53,058] {subprocess.py:92} INFO - File /opt/***/utilities/storage/energy_2.csv does not exist
[2022-11-22 03:12:53,096] {subprocess.py:96} INFO - Command exited with return code 0
[2022-11-22 03:12:53,318] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T031252, end_date=20221122T031253
[2022-11-22 03:12:53,394] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:12:53,583] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:00:20,694] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:00:20,752] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:00:20,754] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:00:20,755] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:00:20,756] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:00:20,830] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:00:20,848] {standard_task_runner.py:52} INFO - Started process 68 to run task
[2022-11-22 04:00:20,866] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp7wp14wa3', '--error-file', '/tmp/tmp6ug2_puc']
[2022-11-22 04:00:20,871] {standard_task_runner.py:80} INFO - Job 120: Subtask checkfiles.check_energy_file_2
[2022-11-22 04:00:20,950] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:00:21,249] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:00:21,858] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:00:21,864] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 04:00:21,868] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/utilities/check_file.sh /opt/***/utilities/storage/energy_2.csv']
[2022-11-22 04:00:21,912] {subprocess.py:85} INFO - Output:
[2022-11-22 04:00:21,944] {subprocess.py:92} INFO - File /opt/***/utilities/storage/energy_2.csv does not exist
[2022-11-22 04:00:21,947] {subprocess.py:96} INFO - Command exited with return code 0
[2022-11-22 04:00:22,155] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T040020, end_date=20221122T040022
[2022-11-22 04:00:22,312] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:00:22,539] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:02:21,444] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:02:21,496] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:02:21,497] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:02:21,499] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:02:21,500] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:02:21,578] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:02:21,599] {standard_task_runner.py:52} INFO - Started process 117 to run task
[2022-11-22 04:02:21,627] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmppyqsztj1', '--error-file', '/tmp/tmp_l_xm12m']
[2022-11-22 04:02:21,634] {standard_task_runner.py:80} INFO - Job 136: Subtask checkfiles.check_energy_file_2
[2022-11-22 04:02:21,724] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:02:22,018] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:02:22,617] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:02:22,626] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 04:02:22,629] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/utilities/check_file.sh /opt/***/utilities/storage/energy_2.csv']
[2022-11-22 04:02:22,681] {subprocess.py:85} INFO - Output:
[2022-11-22 04:02:22,737] {subprocess.py:92} INFO - File /opt/***/utilities/storage/energy_2.csv does not exist
[2022-11-22 04:02:22,745] {subprocess.py:96} INFO - Command exited with return code 0
[2022-11-22 04:02:23,133] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T040221, end_date=20221122T040223
[2022-11-22 04:02:23,239] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:02:23,503] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:12:41,430] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:12:41,492] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:12:41,494] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:12:41,495] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:12:41,496] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:12:41,590] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:12:41,610] {standard_task_runner.py:52} INFO - Started process 168 to run task
[2022-11-22 04:12:41,630] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpuo7ne8f0', '--error-file', '/tmp/tmp42iirk6a']
[2022-11-22 04:12:41,636] {standard_task_runner.py:80} INFO - Job 150: Subtask checkfiles.check_energy_file_2
[2022-11-22 04:12:41,731] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:12:42,061] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:12:42,818] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:12:42,823] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 04:12:42,826] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/utilities/check_file.sh /opt/***/utilities/storage/energy_2.csv']
[2022-11-22 04:12:42,892] {subprocess.py:85} INFO - Output:
[2022-11-22 04:12:42,926] {subprocess.py:92} INFO - File /opt/***/utilities/storage/energy_2.csv does not exist
[2022-11-22 04:12:42,931] {subprocess.py:96} INFO - Command exited with return code 0
[2022-11-22 04:12:43,182] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T041241, end_date=20221122T041243
[2022-11-22 04:12:43,350] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:12:43,777] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:44:24,518] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:24,578] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:24,580] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:24,581] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:44:24,582] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:24,653] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:44:24,669] {standard_task_runner.py:52} INFO - Started process 216 to run task
[2022-11-22 04:44:24,685] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp07ebosbx', '--error-file', '/tmp/tmp9h2bqxlk']
[2022-11-22 04:44:24,690] {standard_task_runner.py:80} INFO - Job 163: Subtask checkfiles.check_energy_file_2
[2022-11-22 04:44:24,756] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:44:25,054] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:44:25,653] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:44:25,659] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 04:44:25,662] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/utilities/check_file.sh /opt/***/utilities/storage/energy_2.csv']
[2022-11-22 04:44:25,708] {subprocess.py:85} INFO - Output:
[2022-11-22 04:44:25,744] {subprocess.py:92} INFO - File /opt/***/utilities/storage/energy_2.csv does not exist
[2022-11-22 04:44:25,749] {subprocess.py:96} INFO - Command exited with return code 0
[2022-11-22 04:44:25,948] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221121T000000, start_date=20221122T044424, end_date=20221122T044425
[2022-11-22 04:44:26,097] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:44:26,463] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
