[2022-12-09 10:35:45,190] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:35:45,257] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:35:45,259] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:35:45,260] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 10:35:45,262] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:35:45,356] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-12-08 00:00:00+00:00
[2022-12-09 10:35:45,383] {standard_task_runner.py:52} INFO - Started process 65 to run task
[2022-12-09 10:35:45,406] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp3wqr91nr', '--error-file', '/tmp/tmpftqv4phl']
[2022-12-09 10:35:45,413] {standard_task_runner.py:80} INFO - Job 4: Subtask checkfiles.check_solar_table
[2022-12-09 10:35:45,490] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-09 10:35:45,777] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 10:35:46,271] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T00:00:00+00:00
[2022-12-09 10:35:46,273] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-12-09 10:35:46,559] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 158, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_solar` isn't defined
[2022-12-09 10:35:46,578] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221208T000000, start_date=20221209T103545, end_date=20221209T103546
[2022-12-09 10:35:46,639] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task checkfiles.check_solar_table (The conn_id `mysql_solar` isn't defined; 65)
[2022-12-09 10:35:46,681] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-09 10:35:46,995] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-09 10:40:59,273] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:40:59,327] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:40:59,329] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:40:59,330] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 10:40:59,331] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:40:59,402] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-12-08 00:00:00+00:00
[2022-12-09 10:40:59,419] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2022-12-09 10:40:59,432] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpxrqs8mdk', '--error-file', '/tmp/tmpmfipbmhd']
[2022-12-09 10:40:59,436] {standard_task_runner.py:80} INFO - Job 17: Subtask checkfiles.check_solar_table
[2022-12-09 10:40:59,502] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-09 10:40:59,710] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 10:41:00,235] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T00:00:00+00:00
[2022-12-09 10:41:00,239] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-12-09 10:41:00,333] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-12-09 10:41:00,511] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-12-09 10:41:00,535] {dbapi.py:216} INFO - Rows affected: 0
[2022-12-09 10:41:00,971] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221208T000000, start_date=20221209T104059, end_date=20221209T104100
[2022-12-09 10:41:01,098] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-09 10:41:01,415] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-09 11:20:30,097] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 11:20:30,139] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 11:20:30,140] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 11:20:30,142] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 11:20:30,143] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 11:20:30,217] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-12-08 00:00:00+00:00
[2022-12-09 11:20:30,256] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2022-12-09 11:20:30,276] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmplgoclsik', '--error-file', '/tmp/tmpztcpxzeq']
[2022-12-09 11:20:30,295] {standard_task_runner.py:80} INFO - Job 47: Subtask checkfiles.check_solar_table
[2022-12-09 11:20:30,457] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-09 11:20:30,879] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-12-08T00:00:00+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 11:20:31,384] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T00:00:00+00:00
[2022-12-09 11:20:31,393] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-12-09 11:20:31,447] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-12-09 11:20:31,561] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-12-09 11:20:31,576] {dbapi.py:216} INFO - Rows affected: 0
[2022-12-09 11:20:31,741] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221208T000000, start_date=20221209T112030, end_date=20221209T112031
[2022-12-09 11:20:31,816] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-09 11:20:32,058] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
