[2022-12-09 10:41:20,192] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.transform.preprocess_geography manual__2022-12-09T10:40:49.230234+00:00 [queued]>
[2022-12-09 10:41:20,239] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.transform.preprocess_geography manual__2022-12-09T10:40:49.230234+00:00 [queued]>
[2022-12-09 10:41:20,240] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:41:20,242] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 10:41:20,243] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:41:20,321] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transform.preprocess_geography> on 2022-12-09 10:40:49.230234+00:00
[2022-12-09 10:41:20,335] {standard_task_runner.py:52} INFO - Started process 163 to run task
[2022-12-09 10:41:20,356] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'transform.preprocess_geography', 'manual__2022-12-09T10:40:49.230234+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmptz696yry', '--error-file', '/tmp/tmp0bj103p1']
[2022-12-09 10:41:20,360] {standard_task_runner.py:80} INFO - Job 30: Subtask transform.preprocess_geography
[2022-12-09 10:41:20,609] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.transform.preprocess_geography manual__2022-12-09T10:40:49.230234+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 10:41:20,952] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=transform.preprocess_geography
AIRFLOW_CTX_EXECUTION_DATE=2022-12-09T10:40:49.230234+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-09T10:40:49.230234+00:00
[2022-12-09 10:41:21,001] {logging_mixin.py:115} INFO - ['altitudeMeridian', 'altitude_09', 'altitude_12', 'altitude_15', 'altitude_18', 'azimuth_09', 'azimuth_12', 'azimuth_15', 'azimuth_18']
[2022-12-09 10:41:21,007] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/preprocess/preprocess.py", line 78, in geography_preprocess
    df[col]=df[col].map(angle_to_float)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 4161, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/base.py", line 870, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/preprocess/preprocess.py", line 64, in angle_to_float
    angle = angle.split('Ëš')
AttributeError: 'int' object has no attribute 'split'
[2022-12-09 10:41:21,086] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=transform.preprocess_geography, execution_date=20221209T104049, start_date=20221209T104120, end_date=20221209T104121
[2022-12-09 10:41:21,135] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task transform.preprocess_geography ('int' object has no attribute 'split'; 163)
[2022-12-09 10:41:21,169] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-09 10:41:21,453] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
