[2022-11-22 05:29:12,110] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-11-22T05:29:06.698630+00:00 [queued]>
[2022-11-22 05:29:12,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-11-22T05:29:06.698630+00:00 [queued]>
[2022-11-22 05:29:12,185] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:29:12,187] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 05:29:12,188] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:29:12,310] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-22 05:29:06.698630+00:00
[2022-11-22 05:29:12,331] {standard_task_runner.py:52} INFO - Started process 536 to run task
[2022-11-22 05:29:12,354] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'manual__2022-11-22T05:29:06.698630+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpa3qp89vu', '--error-file', '/tmp/tmpkotwjggl']
[2022-11-22 05:29:12,361] {standard_task_runner.py:80} INFO - Job 254: Subtask checkfiles.check_weather_table
[2022-11-22 05:29:12,931] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-11-22T05:29:06.698630+00:00 [running]> on host 8a647070b091
[2022-11-22 05:29:13,648] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T05:29:06.698630+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T05:29:06.698630+00:00
[2022-11-22 05:29:13,653] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 05:29:13,716] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 05:29:13,892] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 05:29:13,931] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 05:29:14,177] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221122T052906, start_date=20221122T052912, end_date=20221122T052914
[2022-11-22 05:29:14,328] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 05:29:14,794] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
