[2022-11-22 03:03:45,390] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_1 manual__2022-11-22T03:03:41.711301+00:00 [queued]>
[2022-11-22 03:03:45,470] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_1 manual__2022-11-22T03:03:41.711301+00:00 [queued]>
[2022-11-22 03:03:45,472] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:45,473] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:03:45,475] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:45,552] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_1> on 2022-11-22 03:03:41.711301+00:00
[2022-11-22 03:03:45,568] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2022-11-22 03:03:45,590] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_1', 'manual__2022-11-22T03:03:41.711301+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpat45o1g2', '--error-file', '/tmp/tmpixdp27zd']
[2022-11-22 03:03:45,592] {standard_task_runner.py:80} INFO - Job 86: Subtask checkfiles.check_energy_file_1
[2022-11-22 03:03:45,888] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_1 manual__2022-11-22T03:03:41.711301+00:00 [running]> on host 42206527e50b
[2022-11-22 03:03:46,369] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T03:03:41.711301+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T03:03:41.711301+00:00
[2022-11-22 03:03:46,375] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 03:03:46,378] {subprocess.py:74} INFO - Running command: ['bash', '-c', './utilities/check_file.sh ./storage//opt/***']
[2022-11-22 03:03:46,411] {subprocess.py:85} INFO - Output:
[2022-11-22 03:03:46,424] {subprocess.py:92} INFO - bash: line 1: ./utilities/check_file.sh: No such file or directory
[2022-11-22 03:03:46,426] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 03:03:46,523] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 03:03:46,544] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_1, execution_date=20221122T030341, start_date=20221122T030345, end_date=20221122T030346
[2022-11-22 03:03:46,607] {standard_task_runner.py:97} ERROR - Failed to execute job 86 for task checkfiles.check_energy_file_1 (Bash command failed. The command returned a non-zero exit code 127.; 89)
[2022-11-22 03:03:46,671] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 03:03:46,840] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
