[2022-11-22 04:44:34,053] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.check_input_folder scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:34,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.check_input_folder scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:34,098] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:34,099] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:44:34,100] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:34,168] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_files.check_input_folder> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:44:34,185] {standard_task_runner.py:52} INFO - Started process 230 to run task
[2022-11-22 04:44:34,202] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'load_files.check_input_folder', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp_ko39csb', '--error-file', '/tmp/tmphmrk2wac']
[2022-11-22 04:44:34,206] {standard_task_runner.py:80} INFO - Job 169: Subtask load_files.check_input_folder
[2022-11-22 04:44:34,279] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:44:34,498] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.load_files.check_input_folder scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:44:34,978] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=load_files.check_input_folder
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:44:34,983] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 04:44:34,985] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/make_folder.sh /opt/***/storage/input/2022-11-22']
[2022-11-22 04:44:35,019] {subprocess.py:85} INFO - Output:
[2022-11-22 04:44:35,027] {subprocess.py:92} INFO - bash: line 1: /opt/***/make_folder.sh: No such file or directory
[2022-11-22 04:44:35,029] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 04:44:35,103] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 04:44:35,118] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=load_files.check_input_folder, execution_date=20221121T000000, start_date=20221122T044434, end_date=20221122T044435
[2022-11-22 04:44:35,173] {standard_task_runner.py:97} ERROR - Failed to execute job 169 for task load_files.check_input_folder (Bash command failed. The command returned a non-zero exit code 127.; 230)
[2022-11-22 04:44:35,220] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 04:44:35,444] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
