[2022-11-22 03:09:08,741] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 manual__2022-11-22T03:09:05.840955+00:00 [queued]>
[2022-11-22 03:09:08,859] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_energy_file_2 manual__2022-11-22T03:09:05.840955+00:00 [queued]>
[2022-11-22 03:09:08,861] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:08,862] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:09:08,863] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:08,986] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): checkfiles.check_energy_file_2> on 2022-11-22 03:09:05.840955+00:00
[2022-11-22 03:09:09,004] {standard_task_runner.py:52} INFO - Started process 136 to run task
[2022-11-22 03:09:09,037] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_energy_file_2', 'manual__2022-11-22T03:09:05.840955+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpv8z2ohg9', '--error-file', '/tmp/tmpdl6nij3f']
[2022-11-22 03:09:09,050] {standard_task_runner.py:80} INFO - Job 98: Subtask checkfiles.check_energy_file_2
[2022-11-22 03:09:09,538] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_energy_file_2 manual__2022-11-22T03:09:05.840955+00:00 [running]> on host 42206527e50b
[2022-11-22 03:09:10,221] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_energy_file_2
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T03:09:05.840955+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T03:09:05.840955+00:00
[2022-11-22 03:09:10,231] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-11-22 03:09:10,235] {subprocess.py:74} INFO - Running command: ['bash', '-c', './utilities/check_file.sh ./storage/energy_2.csv']
[2022-11-22 03:09:10,328] {subprocess.py:85} INFO - Output:
[2022-11-22 03:09:10,356] {subprocess.py:92} INFO - bash: line 1: ./utilities/check_file.sh: No such file or directory
[2022-11-22 03:09:10,359] {subprocess.py:96} INFO - Command exited with return code 127
[2022-11-22 03:09:10,499] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-22 03:09:10,520] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_energy_file_2, execution_date=20221122T030905, start_date=20221122T030908, end_date=20221122T030910
[2022-11-22 03:09:10,581] {standard_task_runner.py:97} ERROR - Failed to execute job 98 for task checkfiles.check_energy_file_2 (Bash command failed. The command returned a non-zero exit code 127.; 136)
[2022-11-22 03:09:10,641] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-22 03:09:10,896] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
